// src/app/layout.js  (SIN "use client")
import { AntdRegistry } from "@ant-design/nextjs-registry"; // SSR de AntD v5
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; // tus globales
import Providers from "./providers"; // ConfigProvider en cliente

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Gestión administrativa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <AntdRegistry>
          <Providers>{children}</Providers>
        </AntdRegistry>
      </body>
    </html>
  );
}
